FROM node:20-alpine AS builder

ENV NODE_ENV build


WORKDIR /app

USER node


COPY --chown=node:node package*.json ./
COPY --chown=node:node tsconfig*.json ./
COPY --chown=node:node nest-cli.json ./

RUN npm ci

COPY . .

RUN npm run build

FROM node:20-alpine

WORKDIR /app

COPY --from=builder --chown=node:node /app /app

ENV CI=true
ENV NODE_ENV=test

USER node


VOLUME ["/app/coverage"]



CMD ["sh", "-c", "npm run migration:run:prod && npm run test -- --verbose"]
