FROM node:20-alpine AS builder

WORKDIR /app

COPY package*.json ./
COPY tsconfig*.json ./
COPY nest-cli.json ./

RUN npm ci

COPY . .

RUN npm run build

FROM node:20-alpine

WORKDIR /app

COPY --from=builder /app /app

ENV CI=true
ENV NODE_ENV=test

VOLUME ["/app/coverage"]

CMD ["sh", "-c", "npm run migration:run:prod && npm run test -- --verbose"]
